# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VJk_xziXrEAShA_0hKbC-VeiyqcT2M8_
"""

x = 5
print(f"變數x的值是:" ,x)
print(f"變數x的位址為:" ,id(x))

