# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j4qJEAPfWQdFHYhmUq_ClZQm9NT3QHoN
"""

import sqlite3
conn = sqlite3.connect('BBQ.db')
cursor = conn.cursor()
cursor.execute('''CREATE TABLE IF NOT EXISTS meat(
                  id INTEGER PRIMARY KEY,
                   name TEXT,
                   price INTEGER,
                   quantity INTEGER)''')
cursor.execute("INSERT INTO meat (name, price, quantity) VALUES ('chicken', 30, 5)")
cursor.execute("INSERT INTO meat (name, price, quantity) VALUES ('beaf', 55, 10)")
cursor.execute("INSERT INTO meat (name, price, quantity) VALUES ('pork', 40, 15)")
conn.commit()
print("目前表格內容:")
cursor.execute("SELECT * FROM meat")
for row in cursor.fetchall():
    print(row)
cursor.execute("UPDATE meat SET price = 35 WHERE name = 'pork'")
cursor.execute("UPDATE meat SET quantity = 30 WHERE name = 'chicken'")
conn.commit()
print("\n更新後的表格內容:")
cursor.execute("SELECT * FROM meat")
for row in cursor.fetchall():
    print(row)
cursor.execute("DELETE FROM meat WHERE price = 40")
conn.commit()
print("\n刪除後的表格內容:")
cursor.execute("SELECT * FROM meat")
for row in cursor.fetchall():
    print(row)
conn.close()